.TH Setup-Tool "Version 1.4.99c" "User Manual"

.SH NAME
setup-tool \- Setup-Tool

.SH DESCRIPTION
This program is made to make setting up different things, like codecs and repos, easier on Fedora.
Options of this program are the following:
- Repo Setup
- DNF Modification Tool
- Codec Setup
- Package Management Helper
- Premade Scripts
- System Information
- Update
- System upgrade
- Reboot

Please remember that this program is not part of the Fedora Project and is maintained by a third-party person.

.SH USAGE
To use Setup-Tool, open a terminal and run the following command:

.BR setup-tool

.SH NOTES
This project is maintained by a third-party developer and not part of the Fedora Project.

.SH AUTHOR
Setup Tooling Project <pr_st@burningpho3nix.xyz>

.SH SEE ALSO
https://github.com/Setup-Tooling/Setup-Tool-for-Fedora/blob/stable/README.md

.SH LIMITATIONS
This program is currently only available in the CLI and TUI version.

.SH COPYRIGHT
Copyright (C) 2023 Setup Tooling Project. This is free software; see the source code for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
