.TH Setup-Tool "Version 1.2.3c" "User Manual"

.SH NAME
setup-tool \- Setup-Tool

.SH DESCRIPTION
This program is made to make setting up different things, like codecs and repos, easier on Fedora.
Options of this program are following:
- Repo Setup
- DNF Modification Tool
- Codec Setup
- Package Management Helper
- Premade Scripts
- System Information
- Update
- Reboot

Please remember that this program is not part of the Fedora Project and is maintained by an independent community.

.SH USAGE
To use Setup-Tool, open a terminal and run the following command:

.BR setup-tool

.SH NOTES
This project is maintained by an independent community and not part of the Fedora Project.

.SH AUTHOR
Setup Tooling Project <pr@burningpho3nix.xyz>

.SH SEE ALSO
https://github.com/Setup-Tooling/Setup-Tool-for-Fedora/blob/stable/README.md

.SH LIMITATIONS
This program is currently only available in the CLI version.
The older bash versions support a TUI, but lack some features.

.SH COPYRIGHT
Copyright (C) 2023 Setup Tooling Project. This is free software; see the source code for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
